# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ArbitrageMonitor\ArbitrageDemo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArbitrageMonitor(object):
    def setupUi(self, ArbitrageMonitor):
        ArbitrageMonitor.setObjectName("ArbitrageMonitor")
        ArbitrageMonitor.resize(1512, 536)
        ArbitrageMonitor.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtWidgets.QWidget(ArbitrageMonitor)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1491, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        ArbitrageMonitor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArbitrageMonitor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1512, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        ArbitrageMonitor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArbitrageMonitor)
        self.statusbar.setObjectName("statusbar")
        ArbitrageMonitor.setStatusBar(self.statusbar)
        self.actionAbout_Me = QtWidgets.QAction(ArbitrageMonitor)
        self.actionAbout_Me.setObjectName("actionAbout_Me")
        self.actionExit = QtWidgets.QAction(ArbitrageMonitor)
        self.actionExit.setObjectName("actionExit")
        self.menuAbout.addAction(self.actionAbout_Me)
        self.menuAbout.addAction(self.actionExit)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ArbitrageMonitor)
        QtCore.QMetaObject.connectSlotsByName(ArbitrageMonitor)

    def retranslateUi(self, ArbitrageMonitor):
        _translate = QtCore.QCoreApplication.translate
        ArbitrageMonitor.setWindowTitle(_translate("ArbitrageMonitor", "ArbitrageMonitor"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ArbitrageMonitor", "豆油/豆粕"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ArbitrageMonitor", "豆粕-菜粕"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("ArbitrageMonitor", "豆油-棕榈油"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("ArbitrageMonitor", "菜油-豆油"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("ArbitrageMonitor", "菜油-棕榈油"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("ArbitrageMonitor", "菜油/菜粕"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("ArbitrageMonitor", "玉米淀粉-玉米"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("ArbitrageMonitor", "螺纹钢-热卷"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("ArbitrageMonitor", "螺纹钢/铁矿石"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("ArbitrageMonitor", "焦炭/焦煤"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("ArbitrageMonitor", "L-PP"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("ArbitrageMonitor", "PP-3*MA"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("ArbitrageMonitor", "铝/锌"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("ArbitrageMonitor", "铜/锌"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("ArbitrageMonitor", "金/银"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ArbitrageMonitor", "起始时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ArbitrageMonitor", "最后时间"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ArbitrageMonitor", "价格1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ArbitrageMonitor", "价格2"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ArbitrageMonitor", "现值"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ArbitrageMonitor", "前值"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ArbitrageMonitor", "前10个交易日"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ArbitrageMonitor", "前20个交易日"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ArbitrageMonitor", "前30个交易日"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ArbitrageMonitor", "最小值"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("ArbitrageMonitor", "5%分位"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("ArbitrageMonitor", "均值"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("ArbitrageMonitor", "95%分位"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("ArbitrageMonitor", "最大值"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menuAbout.setTitle(_translate("ArbitrageMonitor", "About"))
        self.actionAbout_Me.setText(_translate("ArbitrageMonitor", "About Me"))
        self.actionExit.setText(_translate("ArbitrageMonitor", "Exit"))
        self.actionExit.setShortcut('Ctrl+Q')
        self.actionExit.setStatusTip('退出应用程序')
        self.actionExit.triggered.connect(QtWidgets.qApp.quit)

        self.actionAbout_Me.triggered.connect(self.do_btn25)

    def do_btn25(self, event):  # 消息：关于
        reply = QtWidgets.QMessageBox.about(self.centralwidget, "关于",
                                            "本软件遵循GPL协议，旨在监控商品期货价差。由于数据来源为新浪接口，所以会有所延迟，敬请见谅。作者：张逸辰，联系方式：ethan@yczhang.cn")

